### ISSUE TITLE
Output size of Adaptation network

### ISSUE THREAD

**Issue by wyinggui** [MADONOKOUKI/Block-wise-Scrambled-Image-Recognition#2]
Thanks alot for sharing your codes. it's a meaningful work.

I have a question about the output of Adaptation Network. For cifar10 dataset, the output size of the adaptive network is 32 * 32 * 16. Why did you select 16 for the channel number? Is choosing a number smaller or larger than 16 OK? How do different values affect the results？

：）  ：）

**Comment by MADONOKOUKI** [comment]
@wyinggui 
I'm sorry for replying to your question too late...
We optimally decide the channel size 16. It means Adaptation Network may show multiple candidates for scramble image's features. It OK to adjust the channel size, and larger channel size improve the classification accuracy and so on.
We did not investigate the result of the difference channel size because it does not relate to the paper's story.
If you have additional questions and want to get the answer quickly, please email my address directly.
